trigger:
- master

pool:
  name: LinuxAgentPool
  demands:
    - Prod -equals Yes

stages:
    - stage: BuildingJavaCode
      jobs:
      - job: BuildingJavaCodeJob
        timeoutInMinutes: 10
        steps:
        - script: echo $(Build.BuildId)
          displayName: 'Display The Build-ID'

        - script: ls -al && pwd
          displayName: 'List Files & Current Working Directory'

        - script: ls -al && chmod 700 build.sh && sudo bash ./build.sh && ls -al
          displayName: 'Run the build script'
        
        - script: ls -al && mv ROOT.war ROOT$(Build.BuildId).war && ls -al
          displayName: 'List Files & Rename ROOT.war'
     
        - script: cp ROOT$(Build.BuildId).war /artifacts && ls -al /artifacts
          displayName: 'Copy WAR to tmp folder'
        - task: CopyFiles@2
          inputs:
            Contents: 'ROOT$(Build.BuildId).war'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
            OverWrite: true
          displayName: 'Copying WAR file to ArtifactStagingDirector'

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'ROOT$(Build.BuildId).war'
            publishLocation: 'Container'
          displayName: 'Publishing WAR Artifact.'

    - stage: CopyingArtifactsToAzureAndAws
      jobs:
      - job: CopyFilesToAzureBlob
        timeoutInMinutes: 10
        steps:
        - checkout: none

        - task: AzureCLI@2
          inputs:
            azureSubscription: 'devopsb24-azure-connection'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az storage blob upload-batch --account-name devopsb24adoartifacts  --account-key $(STORAGE_ACCOUNT_KEY) --destination artifacts --source /artifacts/
          displayName: 'Azure Upload artifacts to Azure Blob'
          continueOnError: true
      - job: CopyFilesToAWSS3Bucket
        dependsOn: CopyFilesToAzureBlob
        timeoutInMinutes: 10
        steps:
        - checkout: none                
        - task: S3Upload@1
          inputs:
            awsCredentials: 'devopsb24-aws-connection'
            regionName: 'us-east-1'
            bucketName: 'devopsb24adoartifacts'
            sourceFolder: '/artifacts/'
            globExpressions: 'ROOT$(Build.BuildId).war'
          displayName: 'AWS Upload artifacts to AWS S3 Bucket'
          continueOnError: true

    - stage: BuildDockerImagePushToDockerHubAndAzureACR
      jobs:
      - job: BuildImageAndPushToDockerHub
        timeoutInMinutes: 10
        steps:
        - checkout: none
        - task: Docker@2
          inputs:
            containerRegistry: 'devopsb24-dockerhub-connection'
            repository: 'sreeharshav/devopsb24adonew'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
          displayName: 'Creating & Pushing Docker Image To Docker Registry HUB'
          continueOnError: true
      - job: BuildIMageAndPushToAzureACR
        dependsOn: BuildIMageAndPushToDockerHub
        timeoutInMinutes: 10
        steps:
        - checkout: none
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              docker login -u devopsb24acr -p $(acrpassword) devopsb24acr.azurecr.io
              docker tag sreeharshav/devopsb24adonew:$(Build.BuildId) devopsb24acr.azurecr.io/devopsb24:$(Build.BuildId)
              docker push devopsb24acr.azurecr.io/devopsb24:$(Build.BuildId)
          displayName: 'Creating & Pushing Docker Image To Azure ACR'

    - stage: DeployDockerImageToAzureACI
      pool:
       name: LinuxAgentPool 
       demands:
         - Prod -equals Yes
      jobs:
      - job: DeployAzureACI
        timeoutInMinutes: 10
        steps:
        - checkout: none
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'devopsb24-azure-connection'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: 'az container create -g DevOpsB24ADORG --name devopsb24aci$(Build.BuildId) --image devopsb24acr.azurecr.io/devopsb24:$(Build.BuildId) --cpu 1 --memory 1 --ports 8080 --dns-name-label devopsb24aci$(Build.BuildId) --registry-username devopsb24acr --registry-password $(acrpassword) --location eastus'
            #inlineScript: az group list
          displayName: 'Deploy Docker Image to Azure Container Instances'
          continueOnError: true          

    - stage: 'DeployingToStagingEnvironment'
      pool: LinuxAgentPool
      displayName: 'Deploying To AWS Staging Environment'
      
      jobs:
      - deployment: "DeployWARtoStagingServer"
        environment: 
          name: STAG
          resourceType: VirtualMachine
        strategy:
          runOnce:
            deploy :
              steps:
               - script: hostname && sudo rm -rf /var/lib/tomcat8/webapps/mywebapp.war
                 displayName: 'Deleting Existing WAR file'
                 continueOnError: true

               - script: cd /home/ubuntu/azagent/_work/1/ && ls -al && rm -rf ROOT.war
                 displayName: 'List Artifact Files'
                 continueOnError: true

               - script: cd /home/ubuntu/azagent/_work/1/ && sudo mv ROOT$(Build.BuildId).war ROOT.war && ls -al ROOT.war
                 displayName: 'Rename Artifact Files'
                 continueOnError: true

               - script: cd /home/ubuntu/azagent/_work/1/ && sudo cp ROOT.war/ROOT$(Build.BuildId).war /var/lib/tomcat8/webapps/mywebapp.war
                 displayName: 'Copy Artifact Files to webapps Folder'
                 continueOnError: true

               - script: sudo rm -rf ROOT*.war
                 displayName: 'Delete Artifact Files'
                 continueOnError: true

    - stage: 'DeployingToPRODEnvironment'
      pool: LinuxAgentPool
      displayName: 'Deploying To AWS Production Environment'
      
      jobs:
      - deployment: "DeployWARtoProdServer"
        environment: 
          name: PROD
          resourceType: VirtualMachine
        strategy:
          runOnce:
            deploy :
              steps:
               - script: hostname && sudo rm -rf /var/lib/tomcat8/webapps/mywebapp.war
                 displayName: 'Deleting Existing WAR file'
                 continueOnError: true

               - script: cd /home/ubuntu/azagent/_work/1/ && ls -al && rm -rf ROOT.war
                 displayName: 'List Artifact Files'
                 continueOnError: true

               - script: cd /home/ubuntu/azagent/_work/1/ && sudo mv ROOT$(Build.BuildId).war ROOT.war && ls -al ROOT.war
                 displayName: 'Rename Artifact Files'
                 continueOnError: true

               - script: cd /home/ubuntu/azagent/_work/1/ && sudo cp ROOT.war/ROOT$(Build.BuildId).war /var/lib/tomcat8/webapps/mywebapp.war
                 displayName: 'Copy Artifact Files to webapps Folder'
                 continueOnError: true

               - script: sudo rm -rf ROOT*.war
                 displayName: 'Delete Artifact Files'
                 continueOnError: true
            
    - stage: DeleteTheRepo
      jobs:
      - job: DeleteTheRepoCntent
        timeoutInMinutes: 10
        steps:
         - checkout: none
         - script: cd /home/adminsree/myagent/_work/1/s && sudo rm -rf src
           displayName: 'Remove Files'

         - script: cd /artifacts && sudo rm -f *.war
           displayName: 'Remove Files From tmp Folder'

